spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: example_route
          uri: https://youtube.com
          predicates:
            - Path=/api/jugamsoft/

          filters:
            - StripPrefix=2  #strip prefix means to strip away a piece of the predictate path, e.g this path=/api/member, stripPrefix=1 will remove /api and leave path=/member

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG